// Generated by CoffeeScript 1.3.2
(function() {

  jQuery(function() {
    var key, mappings, _results;
    mappings = {
      'i': 'up',
      'k': 'down',
      'j': 'counterClockwise',
      'l': 'clockwise',
      'a': 'left',
      'd': 'right',
      's': 'back',
      'f': 'flip',
      'w': 'front',
      'g': 'land',
      't': 'takeoff',
      'space': 'dump'
    };
    _results = [];
    for (key in mappings) {
      _results.push((function(key, mapping) {
        return keypress.register_combo({
          keys: key,
          prevent_repeat: true,
          on_keydown: function() {
            if (mappings[key] == 'dump') {
              socket.emit('dump');
            } else {
              socket.emit('keydown', mappings[key]);
            }
            return console.log(key, 'down', mappings[key]);
          },
          on_keyup: function() {
            if (mappings[key] == 'dump') {
              // socket.emit('dump');
            } else {
              socket.emit('keyup', mappings[key]);
            }
            return console.log(key, 'up', mappings[key]);
          }
        });
      })(key, mappings[key]));
    }
    return _results;
  });

}).call(this);
